### ISSUE TITLE
The save as new button is visible in the Subsection manager

### ISSUE THREAD

**Issue by nitriques** [symphonists/duplicate_entry#4]
I don't think that it's a good idea that this button shows up un the subsection manager.

I don't even know if the fix should be applied in this extension or in nils'.

But I did a similar fix in my save and return exception and I just wanted to let you know.

**Comment by nickdunn** [comment]
@nilshoerrmann how do you think we should proceed — how does SSM hide core elements in the UI?

**Comment by nilshoerrmann** [comment]
It's a mixture of DOM modifications and additional CSS:

Subsection Manager removes unneeded parts of the interface like the header using JavaScript and it applies special styling to generate the dark inline view on an entry. In this context, SSM takes care of all core fields but not any other third party extension. 

If an entry is viewed inside SSM, the extensions applies two additional classes to the `body` – `.inline.subsection` – which you can use inside your extension to hide the `Save as new` button.

**Comment by nitriques** [comment]
This is what I have done for my save and return extension, (adding a particular css when body has inline.subsection)

**Comment by nickdunn** [comment]
Nic, would you mind sending a pull request please, or pointing me to where you added your fix?

**Comment by nitriques** [comment]
Yes, see https://github.com/nickdunn/duplicate_entry/pull/5
