### ISSUE TITLE
installation issue on symphony 2.2.5

### ISSUE THREAD

**Issue by danielepennati** [symphonists/duplicate_entry#8]
Hello
I've tried to install duplicate entry on symphony 2.2.5 but I'm not abele to do that...
I have upload the duplicate entry folder in the extention folder
Than I went to the extension page in the back end but I got a black page
do you have any advice to fix this issue?
Thanks
Daniele

**Comment by nitriques** [comment]
Closing as this is an old issue and there are no problems with install
